SoEasyTeam/Dev.Town

src/components/common/Comment.jsx
=> Style: border 색상 변경

src/components/common/Comment.jsx
=> Style: 위치 수정, placeholder 패딩값 설정

src/components/common/Comment.jsx, src/components/common/HomeImgPost.jsx, src/components/common/HomePost.jsx, src/components/common/Product.jsx, src/components/common/TabMenu.jsx, src/components/common/TopNav.jsx
Common components 이슈 해결 및 속성 변경
=> Common components 이슈 해결 및 속성 변경

src/App.jsx, src/components/common/HomeImgPost.jsx, src/components/common/HomePost.jsx, src/components/common/Product.jsx
HomePost 및 ProductPrice 속성 값 수정입니다.
=> HomePost 및 ProductPrice 속성 값 수정

src/components/common/HomeImgPost.jsx, src/components/common/HomePost.jsx
HomePost 및 HomeImgPost style 속성 수정
=> HomePost 및 HomeImgPost style 속성 수정

src/components/common/Buttons.jsx
수정한 부분들
1. 버튼 UI 컴포넌트에서 기존의 LBtns, MBtns 등 뒤에 s가 붙는 것을 삭제했습니다.
2. 컴포넌트 내에서가 아니라 기능 부분은 따로 다른 파일에서 코드를 구현하자고 결정하였지만, 코드를 수정하다보니 한 가지 기능만 수행하는 버튼들이 몇 개 있어서 그런 버튼들만 제외하고 나머지 2가지 이상 기능을 수행하는 버튼들은 props 관련 코드를 삭제하였습니다. (하단의 버튼 함수들도 삭제) **두가지 이상 기능을 하는 버튼들은 어떤 기능들을 수행할 수 있는지 따로 주석도 달아놓았습니다🙌
3. 다른 크기의 버튼 하나가 누락되어서 MlBtn 이라는 컴포넌트를 추가했습니다.
확인 후 리뷰 부탁드립니다!
=> Refactor : Button 컴포넌트 수정

src/components/common/TextAciveInput.jsx
=> Style: 이메일, 비밀번호 width 수정

src/components/common/TextAciveInput.jsx
=> Style: 이메일,비밀번호 width 수정

src/components/common/TopNav.jsx
=> Style: FollowNav 추가

src/components/common/UserSearch.jsx
=> Style: UserSearchBox width 수정

src/App.jsx, src/pages/LoginPage.jsx
=> Feat: Login page 추가

package-lock.json, package.json, src/App.jsx, src/components/loginOptions/LoginOptions.jsx, src/index.js, src/pages/JoinMembershipPage.jsx, src/pages/LoginPage.jsx, src/pages/ProfileSettingPage.jsx, src/pages/SplashPage.jsx, src/redux/actions/authenticateAction.js, src/redux/actions/joinAction.js, src/redux/reducers/authenticateReducer.js, src/redux/reducers/index.js, src/redux/reducers/joinReducer.js, src/redux/store.js
=> 로그인 기능 구현 완료 예외처리 제외

src/components/common/HomeImgPost.jsx, src/components/common/HomePost.jsx
홈페이지 포스트 및 이미지 포스트 div -> Link로 변경
=> 홈페이지 포스트 div에서 Link로 변경

src/redux/actions/authenticateAction.js, src/redux/reducers/authenticateReducer.js
password를 휘발성으로 날리고 id, username, email, accountname, image, token을 가져왔습니다.
=> 로그인 리듀서 값 수정

src/App.jsx, src/components/common/TopNav.jsx, src/features/UserProfile.jsx, src/pages/AddProductPage.jsx, src/redux/actions/addProductAction.js, src/redux/reducers/addProductReducer.js, src/redux/reducers/index.js
구현사항
1. 상품 추가 리덕스 세팅
2. 상품 추가 기능 구현
미구현사항
1. 이미지 서버로 업로드
2. 예외처리 (필수 입력 사항 및 가격 입력 숫자 제한)
=> 상품 추가 기능 구현 img제외 및 예외처리 X

src/components/common/HomeImgPost.jsx, src/components/common/HomePost.jsx, src/components/home/HomeFeedBox.jsx, src/pages/HomePage.jsx, src/redux/actions/homeFeedAction.js, src/redux/reducers/addProductReducer.js, src/redux/reducers/authenticateReducer.js, src/redux/reducers/homeFeedReducer.js, src/redux/reducers/index.js, src/redux/reducers/joinReducer.js, src/redux/reducers/profileReducer.js
1. 홈피드 화면
- 피드는 사용자들이 올린 게시글들이 표시되는 페이지입니다.
- 피드에는 자신이 팔로우한 사용자의 게시글만 확인할 수 있습니다.
- 팔로우한 사용자가 없을 경우와 내가 팔로우한 사용자가 올린 게시글이 없는 경우 "유저를 검색해 팔로우 해보세요!" 문구와 함께 '검색하기' 버튼이 표시됩니다.
2. HomeImgPost 수정
- img가 없으면 img 태그를 제외하고 반환할 수 있도록 수정하였습니다.
=> 홈페이지 구현 완료 및 HomeImgPost 수정

src/features/UserPost.jsx, src/features/UserProduct.jsx
=> Fix: 게시물 빈화면 에러 수정

src/App.jsx, src/components/common/TopNav.jsx, src/features/Modal.jsx, src/features/UserProfile.jsx, src/redux/reducers/authenticateReducer.js
userid 받아오기 에러 수정과 topnav 뒤로가기 기능 구현입니다.
=> Styled: topnav 뒤로가기 구현 및 id 에러 수정

src/App.jsx, src/pages/HomePage.jsx, src/pages/LoginPage.jsx, src/redux/actions/authenticateAction.js, src/redux/actions/homeFeedAction.js
1. 로그인 실패시 정보가 맞지 않다고 경고문 출력
2. 로그인 했을 때 로컬 스토리지에 토큰 저장 새로고침할 때 토큰이 날라가지 않음
=> login 예외처리 및 로컬스토리지 토큰 저장

src/components/loginOptions/LoginOptions.jsx
첫 페이지 (로그인/회원가입)
- css 깨지는 부분 전체 수정 
- 마우스호버 지정
=> Styled: loginoption 페이지 스타일 수정

src/App.jsx, src/components/common/TopNav.jsx, src/components/common/UserFollow.jsx, src/components/profile/UserProfile.jsx, src/pages/FollowerPage.jsx, src/pages/FollowingPage.jsx
profile 페이지
- 팔로워, 팔로잉 클릭시 페이지로 이동
- 팔로워, 팔로잉 페이지 구현
=> 팔로워, 팔로잉 페이지 구현

src/App.jsx, src/components/common/AlertModal.jsx, src/components/common/HomeImgPost.jsx, src/components/common/HomePost.jsx, src/components/common/Modal.jsx, src/components/common/Product.jsx, src/components/profile/UserPost.jsx, src/components/profile/UserProduct.jsx, src/pages/MyProfile.jsx, src/redux/actions/profileAction.js
homepost 파일을 homeimgpost에 합쳤습니다.
homepost파일 지워도 되는데, 혹시몰라서 전체 주석처리한 상태로 올렸습니다.
- 상품 클릭시 url로 이동 기능 구현
- alert 삭제창 UI 구현
=> homeimgpost 합치기 및 alert 삭제창 구현

src/App.jsx, src/components/common/ProfileButtons.jsx, src/components/profile/UserProfile.jsx, src/pages/HomePage.jsx, src/pages/JoinMembershipPage.jsx, src/pages/LoginPage.jsx, src/pages/ProfileSettingPage.jsx, src/redux/actions/homeFeedAction.js, src/redux/actions/joinAction.js, src/redux/actions/joinAction.jsx, src/redux/reducers/index.js, src/redux/reducers/joinReducer.js
1. 회원가입 예외처리
2. 회원가입 이미지 업로드 기능 추가
3. 이미지 프로필 연결
=> Feat: 회원가입 예외처리 및 이미지 업로드

src/App.jsx, src/components/common/HomeImgPost.jsx, src/components/home/HomeFeedBox.jsx
1. HomePage 피드 게시물 링크 범위 수정하였습니다.
=> Perf: HomePage Link 범위 수정

src/components/home/HomeFeedBox.jsx
=> Fix: 홈페이지 Link 중복 버그 수정

src/components/common/Modal.jsx, src/components/profile/UserProduct.jsx, src/redux/actions/productAcition.js
=> Feat: 상품 삭제 구현 완료

src/pages/PostUploadPage.jsx, src/redux/actions/commentListAction.js, src/redux/actions/postAction.js
=> Feat: 게시물 업로드 기능 구현 

src/components/profile/UserProfile.jsx, src/index.js, src/pages/HomePage.jsx, src/redux/actions/authenticateAction.js, src/redux/actions/homeFeedAction.js, src/redux/reducers/authenticateReducer.js, src/redux/reducers/index.js, src/redux/store.js
=> Fix: 새로고침 문제 해결

src/components/Splash/index.jsx, src/components/Splash/index.style.js, src/components/login/LoginMain/index.jsx, src/components/login/LoginMain/index.style.js, src/components/login/LoginOptions/index.jsx
=> Refactor: 폴더 관리

src/components/common/alert/index.jsx, src/components/common/modal/index.jsx, src/components/login/LoginMain/index.jsx, src/components/profile/userProduct/index.jsx, src/pages/HomePage.jsx, src/pages/MyProfile.jsx, src/redux/actions/authenticateAction.js, src/redux/reducers/authenticateReducer.js
=> Refactor: 세션스토리지 추가

src/components/login/LoginMain/index.jsx, src/redux/actions/authenticateAction.js, src/redux/actions/homeFeedAction.js, src/redux/actions/joinAction.js, src/redux/actions/postAction.js, src/redux/actions/productAcition.js, src/redux/actions/profileAction.js, src/redux/actions/searchAction.js, src/redux/actions/tokenValidation.js
1. 로그인 예외처리
2. 리덕스 API fetch 방법에서 axios로 변경
=> Refactor: 로그인 예외처리 및 리덕스 actions fetch -> axios로 변경

src/components/list/followList/index.jsx
팔로우리스트 페이지에서 팔로우버튼 활성화 기능구현입니다.
=> Fix: followpage에서 팔로우버튼 활성화

src/components/common/alert/index.jsx, src/components/login/LoginMain/index.jsx, src/pages/SplashPage.jsx, src/redux/Nav.jsx, src/redux/actions/authenticateAction.js, src/redux/reducers/authenticateReducer.js
=> Refactor: 로그아웃 기능 추가

src/pages/Error404Page.jsx, src/pages/HomePage.jsx, src/pages/MyProfile.jsx, src/redux/actions/homeFeedAction.js, src/redux/reducers/authenticateReducer.js
1. 홈피드 및 프로필 토큰 검증 값이 true가 아닐 때 404 페이지로 이동
ex) 로그인을 하지 않고 쿼리문을 통해 바로 home이나 myprofile로 이동하는 경우
=> Refactor: 프로필 및 홈피드 새로고침 기능 수정

src/components/profile/userProfile/index.jsx
상대방프로필페이지에서 팔로우 버튼 클릭시 즉각적으로 팔로우수 변경되는 기능입니다.
=> Feat: 팔로우,언팔로우시 팔로워카운트 업데이트

src/components/login/LoginMain/index.jsx, src/components/profile/userProduct/index.jsx, src/pages/YourProfile.jsx, src/redux/Nav.jsx, src/redux/actions/authenticateAction.js, src/redux/actions/productAcition.js
=> Refactor: 상대프로필 상품리스트 페이지 수정

README.md, src/components/common/button/index.jsx, src/components/common/button/index.style.jsx, src/components/list/followList/index.jsx, src/components/list/followList/index.style.jsx, src/components/profile/userPost/index.jsx, src/components/profile/userProfile/index.jsx, src/components/profile/userProfile/index.style.jsx, src/pages/MyProfile.jsx, src/pages/YourProfile.jsx
=> Refactoring: 상대 프로필 게시물 경로 수정

src/components/common/alert/index.jsx, src/components/profile/userProduct/index.jsx, src/pages/MyProfile.jsx, src/pages/ProfileModificationPage.jsx
=> Refactor: 상품리스트 삭제 즉시 반영

src/components/common/HomeImgPost/index.style.jsx, src/components/common/alert/index.jsx, src/components/common/product/index.style.jsx, src/components/join/ProfileSetting/index.style.js, src/components/login/LoginMain/index.jsx, src/components/product/AddProduct/index.jsx, src/components/product/AddProduct/index.style.js, src/components/product/ProductModification/index.style.js, src/components/profile/userProduct/index.jsx, src/components/profile/userProfile/index.style.jsx, src/pages/ProfileModificationPage.jsx
1. 이미지 ratio 맞추기 수정(상품, 프로필, 게시물)
2. 로그아웃 로그인 토큰 검증 예외처리 수정
3. 상품 리스트 즉시 반영
=> Refactoring: 이미지 ratio 맞추기, 로그아웃 로그인 토큰 검증, 상품리스트 즉시 반영

src/components/common/nav/index.style.jsx, src/components/login/LoginMain/index.jsx, src/pages/SearchPage.jsx, src/pages/YourProfile.jsx
1. 검색 기능 적용
2. 검색 리스트 창 style 추가
=> Feat: 검색 기능 적용

src/components/join/JoinMemberShip/index.jsx, src/components/join/ProfileSetting/index.jsx, src/components/login/LoginMain/index.jsx, src/components/product/AddProduct/index.jsx, src/components/product/ProductModification/index.jsx, src/pages/ProfileModificationPage.jsx, src/redux/Nav.jsx, src/redux/actions/joinAction.js, src/redux/actions/productAcition.js, src/redux/actions/profileAction.js, src/redux/reducers/authenticateReducer.js, src/redux/reducers/productReducer.js
=> Refactor: 이미지 파일 크기 예외처리

src/components/common/HomeImgPost/LkePostRowBox/index.jsx, src/components/common/HomeImgPost/index.jsx, src/components/profile/userPost/index.jsx
=> Feat: 좋아요 기능 구현

src/components/list/followList/index.jsx, src/components/profile/userPost/index.jsx, src/components/profile/userProfile/index.jsx, src/constants/defaultUrl.js, src/pages/FollowerPage.jsx, src/pages/FollowingPage.jsx, src/pages/MyProfile.jsx, src/pages/SearchPage.jsx, src/pages/YourProfile.jsx, src/redux/actions/postAction.js
=> Feat : API 주소 변경

src/components/common/HomeImgPost/index.jsx
변경사항
- 사용자 이미지가 로드되지 못할 경우 default 이미지 설정
=> Refactor : 사용자 이미지가 로드되지 못할 경우 default 이미지 설정
